export default {
    UPDATE_PAGE: 'UPDATE_PAGE',
    UPDATE_OFFLINE: 'UPDATE_OFFLINE',
    UPDATE_DRAWER_STATE: 'UPDATE_DRAWER_STATE',
    OPEN_SNACKBAR: 'OPEN_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR'
};
